---
title: "data explore"
author: "Jingjing Li"
date: "7/24/2021"
output: html_document
  toc: true
---
# packages
```{r}
library(readr)
library(dplyr)
library(stats)
library(corrplot)
library(ggplot2)
library(DT)
library(caret)
library(tree)
```


# data page 
```{r}
  heartData <- read_csv("heart_failure_clinical_records_dataset.csv")

  heartData$age2 <- cut(heartData$age, c(0,40,50,60,70,80,100) )
  heartData2 <- mutate(heartData, age2)
  set.seed (20)
  samplNum <- 0.7
  train <- sample(1:nrow(heartData), size=nrow(heartData)*samplNum )
  trainData <- heartData[train, ]
  test  <- setdiff(1:nrow(heartData),train )
  testData <- heartData[test, ]
  heartDT<- datatable(heartData)
  heartDT
  trainDT<- datatable(trainData)
  trainDT
  testDT<- datatable(testData)
  testDT
```
## subset column data for scroll

```{r}

    mincol <- 1
    maxcol <- 13
   outputcol <- DT::datatable (heartData[, mincol:maxcol])
   outputcol
```

## subset row data for scroll

```{r}

    minrow <- 1
    maxrow <- 20
   outputcol <- DT::datatable (heartData[minrow:maxrow,])
   outputcol
```

# summary
## table summary 
* input variables, quantile number, 
```{r}
var <- "serum_sodium"
heartData %>% group_by(sex) %>% summarise (Avg=mean(serum_sodium))
heartData %>% filter(sex==0) %>% summarise (Avg=mean(serum_sodium))
heartData %>% filter(sex==0) %>% summarise (median=median(serum_sodium))
Min <-heartData %>% filter(sex==0) %>% summarise (Minimum=min(serum_sodium))
heartData %>% filter(sex==0) %>% summarise (Maximum=max(serum_sodium))
Quantile <- heartData %>% filter(sex==0) %>% summarise ("25%"=quantile(serum_sodium, probes=0.9))
 summarise (heartData, Avg=mean(serum_sodium))

heartData %>% filter(sex==0) %>% summary(heartData$serum_sodium)
hecor(heartData)
table(heartData2$age2,heartData2$high_blood_pressure)

data.frame("serum_sodium", summarise (heartData, Avg=mean(serum_sodium)))

   if (input$sumtype =="mean") {data.frame(input$var,summarise (Avg=mean(input$var)))}
    if (input$sumtype =="median") {data.frame(input$var,summarise (Median=median(input$var)))}
    if (input$sumtype =="min") {data.frame(input$var,summarise (Min=min(input$var)))}
    if (input$sumtype =="maxi") {data.frame(input$var,summarise (Maxi=max(input$var)))}
    if (input$sumtype =="sd") {data.frame(input$var,summarise (SD=sd(input$var)))}
 heartData$sex <- as.factor(heartData$sex)
    table <- table(heartData$sex, heartData$age2)
```
## plot summary
### boxplot
```{r}
g1<- ggplot(heartData, aes (x= as.factor(sex), y=platelets, color=sex))
g1+ geom_boxplot()+  geom_jitter(alpha=0.5)

    p <- plot_ly(data=heartData2, x=~creatinine_phosphokinase,y=~ejection_fraction, type = 'scatter', mode="text")
    p
```

### barplot
```{r}
 g2<- ggplot(heartData2,aes(x=age2))
g2+ geom_bar()

```

### scatterplot
```{r}
g3 <-ggplot(heartData,aes(x=serum_creatinine, y=platelets))
g3 + geom_point()
```

### histogram
```{r}
g4 <-ggplot(heartData, aes(x=serum_creatinine))
g4+geom_histogram()
```
# Modeling  
```{r}
 heartData <- read_csv("heart_failure_clinical_records_dataset.csv")
  heartData$age2 <- cut(heartData$age, c(0,40,50,60,70,80,100) )
  heartData2 <- mutate(heartData, age2)
  set.seed (20)
  samplNum <- 0.7
  train <- sample(1:nrow(heartData), size=nrow(heartData)*samplNum )
  trainData <- heartData[train, ]
  test  <- setdiff(1:nrow(heartData),train )
  testData <- heartData[test, ]
  heartDT<- datatable(heartData)
  heartDT
  trainDT<- datatable(trainData)
  trainDT
  testDT<- datatable(testData)
  testDT
```

## Modeling info  
## Modeling Fitting
```{r}

trCntrl <- trainControl(method="repeatedcv", number=10, repeats=5)
```

### Linear Regression
```{r}
linMod <- train(
  as.factor(DEATH_EVENT) ~ age + anaemia + creatinine_phosphokinase + diabetes + ejection_fraction  , 
  data=trainData, 
  method="glm",
  family="binomial",
  trControl=trCntrl,
  na.action = na.exclude
  )
linMod
linMod$results$Accuracy
```

### Tree
```{r}
tGrid <- expand.grid(cp = seq(0, 0.05, .003))
treeMod <- train(
 as.factor(DEATH_EVENT) ~ ., 
  data=trainData, 
  method="rpart",
  preProcess=c("center","scale"),
    trControl=trCntrl,
   na.action = na.exclude,
  tuneGrid=tGrid
  )

treeMod
max(treeMod$results$Accuracy)
```

### Random forest
```{r}
# rfFit <- train (
#  as.factor(DEATH_EVENT) ~ ., 
#  data=trainData,
#  method="rf",
#  preProcess= c("center", "scale"),
#  trControl = trCntrl,
#  metric="Accuracy",
#  tuneGrid=expand.grid(mtry=sqrt(ncol(trainData))),
#   na.action = na.exclude,
 # )
trainData$DEATH_EVENT <- as.factor(trainData$DEATH_EVENT)
rfMod<- train (DEATH_EVENT ~ ., 
               data=trainData,
               method = "rf",
               trControl =  trCntrl,
               preProcess = c("center", "scale"),
                na.action = na.exclude
               )
rfMod

```
### Comparison
```{r}
testData$DEATH_EVENT <- as.factor(testData$DEATH_EVENT)
pred_LM <- predict(linMod, newdata=testData)
pred_TM <- predict(treeMod, newdata=testData )
pred_RM <- predict(rfMod, newdata=testData )
LM <-confusionMatrix(pred_LM, testData$DEATH_EVENT)
TM <-confusionMatrix(pred_TM, testData$DEATH_EVENT)
RM <-confusionMatrix(pred_RM, testData$DEATH_EVENT)

mis_LM <- round (1- sum(diag(LM$table))/sum(LM$table),3)
mis_TM <- round(1- sum(diag(TM$table))/sum(LM$table),3)
mis_RM <- round(1- sum(diag(RM$table))/sum(LM$table),3)
misclassDf <- data.frame(c("linMod","treeMod","rfMod"),c(mis_LM,mis_TM, mis_RM))
rename(misclassDf, "Model"=c..linMod....treeMod....rfMod..,"Misclass"=c.mis_LM..mis_TM..mis_RM.)  
misclassDf

```

## Prediction
```{r}
preditc(linMod, newdata=data.frame( age=25, anaemia=1,creatinine_phosphokinase=, diabetes, ejection_fraction = , high_blood_pressure =, platelets = serum_creatinine =,serum_sodium =sex =smoking = time =)))

```

